import mysql.connector as mycon
def activity():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('activity',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table activity')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table activity(sno int,name varchar(80),no_people int,duration varchar(80))')
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into activity values({},'{}',{},'{}')".format(1,'KARAOKE NIGHT',4,'3 HOURS'))
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into activity values({},'{}',{},'{}')".format(2,'OFFICE COOK OFF',3,'4 HOURS'))
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into activity values({},'{}',{},'{}')".format(3,'PUZZLE PLAY',4,'1 HOURS'))
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into activity values({},'{}',{},'{}')".format(4,'SCAVENGER HUNT',2,'1 HOURS'))
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into activity values({},'{}',{},'{}')".format(5,'RANGOLI MAKING',4,'1 HOURS'))
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into activity values({},'{}',{},'{}')".format(6,'ESCAPE ROOM',5,'1 HOURS'))
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into activity values({},'{}',{},'{}')".format(7,'SHOW AND TELL',3,'1 HOURS'))
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into activity values({},'{}',{},'{}')".format(8,'TWO TRUTHS AND A LIE',5,'1 HOURS'))
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into activity values({},'{}',{},'{}')".format(9,'GROUP VOLENTEER OUTING',3,'1 HOURS'))
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into activity values({},'{}',{},'{}')".format(10,'TWO HEADED MONSTER',2,'1 HOURS'))
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into activity values({},'{}',{},'{}')".format(11,'SUSHI EATING',1,'1/2 HOURS'))
    obj.commit()
    obj.close()
def applicants():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('applicants',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table applicants')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table applicants(sno int,name varchar(80),age int,degree varchar(80),graduated_from varchar(100),expir_years int,innovations varchar(200))')
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(1,'BRAD HUSTON',25,'B.TECH','CAMBRIDGE UNIVERSITY',0,'0 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(2,'MARTIN SCORSECE',27,'B.TECH','HARVARD UNIVERSITY',1,'0 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(3,'BRAD PITT',27,'B.TECH','CAMBRIDGE UNIVERSITY',1,'1 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(4,'LEO DICAPRO',29,'B.TECH','CAMBRIDGE UNIVERSITY',2,'1 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(6,'BON JOON HO',30,'B.TECH+MA(computers)','CAMBRIDGE UNIVERSITY',0,'0 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(7,'SHAH RUKH KHAN',31,'B.TECH+MA(computers)','CAMBRIDGE UNIVERSITY',1,'0 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(8,'AMITABH BACCHAN',32,'B.TECH+MA(computers)','CAMBRIDGE UNIVERSITY',1,'1 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(9,'AKSHAY KUMAR',33,'B.TECH+MA(computers)','CAMBRIDGE UNIVERSITY',2,'1 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(10,'SHINCHAN NOHORA',34,'B.TECH+MA(computers)','CAMBRIDGE UNIVERSITY',2,'2 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(11,'KYLIE JENNER',35,'B.TECH+M.TECH','CAMBRIDGE UNIVERSITY',2,'0 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(12,'NATASHA RAN',36,'B.TECH+M.TECH','CAMBRIDGE UNIVERSITY',2,'1 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(13,'KATE WINSLEY',37,'B.TECH+M.TECH','CAMBRIDGE UNIVERSITY',2,'2 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(14,'KIM UN SUN',38,'B.TECH+M.TECH','CAMBRIDGE UNIVERSITY',2,'3 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(15,'NATALIE NOLAN',39,'B.TECH+M.TECH','CAMBRIDGE UNIVERSITY',2,'4 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(16,'AMANDA DE SANTA',40,'B.TECH+M.TECH','CAMBRIDGE UNIVERSITY',3,'0 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(17,'KAREENA KAPOOR',41,'B.TECH+M.TECH','CAMBRIDGE UNIVERSITY',3,'1 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(18,'KARISHMA KAPOOR',42,'B.TECH+M.TECH','CAMBRIDGE UNIVERSITY',3,'2 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(19,'KATRINA KAIF',43,'B.TECH+M.TECH','CAMBRIDGE UNIVERSITY',3,'2 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(20,'ANUSHKA SHARMA',44,'B.TECH+M.TECH','CAMBRIDGE UNIVERSITY',3,'3 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(21,'DAVID ATTENBROUGH',45,'B.TECH+M.TECH','CAMBRIDGE UNIVERSITY',4,'0 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(22,'GLENN MAXWELL',46,'B.TECH+M.TECH','CAMBRIDGE UNIVERSITY',4,'1 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(23,'VIRAT KOHLI',47,'B.TECH+M.TECH','CAMBRIDGE UNIVERSITY',4,'2 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(24,'DON BRADMAN',48,'B.TECH+M.TECH','CAMBRIDGE UNIVERSITY',4,'3 PATENTS'))
    obj.commit()
    cur.execute("insert into applicants values({},'{}',{},'{}','{}',{},'{}')".format(25,'SACHIN TANDULKAR',49,'B.TECH+M.TECH','CAMBRIDGE UNIVERSITY',4,'4 PATENTS'))
    obj.commit()
    obj.close()
def catalog():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('catalog',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table catalog')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table catalog(sno varchar(5),type varchar(60),model varchar(60),max_seats int,colours varchar(60),emi_interest varchar(60),base_price int)')
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into catalog values('{}','{}','{}',{},'{}','{}',{})".format('1','HATCHBACK','S',2,'CUSTOM','12',45000))
    obj.commit()
    cur.execute("insert into catalog values('{}','{}','{}',{},'{}','{}',{})".format('2','HATCHBACK','X',4,'CUSTOM','12',48000))
    obj.commit()
    cur.execute("insert into catalog values('{}','{}','{}',{},'{}','{}',{})".format('3','HATCHBACK','Y',8,'CUSTOM','12',55000))
    obj.commit()
    cur.execute("insert into catalog values('{}','{}','{}',{},'{}','{}',{})".format('4','SUV','M',4,'CUSTOM','10',65000))
    obj.commit()
    cur.execute("insert into catalog values('{}','{}','{}',{},'{}','{}',{})".format('5','SUV','C',7,'CUSTOM','10',70000))
    obj.commit()
    cur.execute("insert into catalog values('{}','{}','{}',{},'{}','{}',{})".format('6','SUV','D',8,'CUSTOM','10',80000))
    obj.commit()
    cur.execute("insert into catalog values('{}','{}','{}',{},'{}','{}',{})".format('8','SEDAN','T',2,'CUSTOM','8',120000))
    obj.commit()
    cur.execute("insert into catalog values('{}','{}','{}',{},'{}','{}',{})".format('9','SEDAN','Z',4,'CUSTOM','8',150000))
    obj.commit()
    cur.execute("insert into catalog values('{}','{}','{}',{},'{}','{}',{})".format('10','SEDAN','F',4,'CUSTOM','6',200000))
    obj.commit()
    obj.close()
def deca_catalog():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('deca_catalog',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table deca_catalog')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table deca_catalog(SPECIFICATION VARCHAR(60),DETAILS VARCHAR(60))')
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into deca_catalog values('{}','{}')".format('CAR NAME','DECA'))
    obj.commit()
    cur.execute("insert into deca_catalog values('{}','{}')".format('POWER STEARING','YES'))
    obj.commit()
    cur.execute("insert into deca_catalog values('{}','{}')".format('AIRBAGS','10'))
    obj.commit()
    cur.execute("insert into deca_catalog values('{}','{}')".format('FOR LIGHT','YES'))
    obj.commit()
    cur.execute("insert into deca_catalog values('{}','{}')".format('AIR CONDITIONER','YES'))
    obj.commit()
    cur.execute("insert into deca_catalog values('{}','{}')".format('WARRENTY','25 YEARS'))
    obj.commit()
    cur.execute("insert into deca_catalog values('{}','{}')".format('CHARGING TIME','11 HOURS'))
    obj.commit()
    cur.execute("insert into deca_catalog values('{}','{}')".format('DISTANCE WITH SINGLE CHARGE','500 Km'))
    obj.commit()
    cur.execute("insert into deca_catalog values('{}','{}')".format('FUEL TYPE','ELECTRIC'))
    obj.commit()
    cur.execute("insert into deca_catalog values('{}','{}')".format('BOOT SPACE','600 Lts'))
    obj.commit()
    cur.execute("insert into deca_catalog values('{}','{}')".format('ADDITIONAL QUALITIES','OFF ROADER'))
    obj.commit()
    cur.execute("insert into deca_catalog values('{}','{}')".format('PRICE','80000 $'))
    obj.commit()
    cur.execute("insert into deca_catalog values('{}','{}')".format('PRICE+TAX','90000$'))
    obj.commit()
    cur.execute("insert into deca_catalog values('{}','{}')".format('SEATS','8'))
    obj.commit()
    obj.close()
def coulomb_catalog():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('coulomb_catalog',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table coulomb_catalog')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table coulomb_catalog(SPECIFICATION VARCHAR(60),DETAILS VARCHAR(60))')
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into coulomb_catalog values('{}','{}')".format('CAR NAME','CLOULOMB'))
    obj.commit()
    cur.execute("insert into coulomb_catalog values('{}','{}')".format('POWER STEARING','NO'))
    obj.commit()
    cur.execute("insert into coulomb_catalog values('{}','{}')".format('AIRBAGS','8'))
    obj.commit()
    cur.execute("insert into coulomb_catalog values('{}','{}')".format('FOR LIGHT','YES'))
    obj.commit()
    cur.execute("insert into coulomb_catalog values('{}','{}')".format('AIR CONDITIONER','YES'))
    obj.commit()
    cur.execute("insert into coulomb_catalog values('{}','{}')".format('WARRENTY','24 YEARS'))
    obj.commit()
    cur.execute("insert into coulomb_catalog values('{}','{}')".format('CHARGING TIME','10 HOURS'))
    obj.commit()
    cur.execute("insert into coulomb_catalog values('{}','{}')".format('DISTANCE WITH SINGLE CHARGE','600 Km'))
    obj.commit()
    cur.execute("insert into coulomb_catalog values('{}','{}')".format('FUEL TYPE','ELECTRIC'))
    obj.commit()
    cur.execute("insert into coulomb_catalog values('{}','{}')".format('BOOT SPACE','450 Lts'))
    obj.commit()
    cur.execute("insert into coulomb_catalog values('{}','{}')".format('ADDITIONAL QUALITIES','OFF ROADER'))
    obj.commit()
    cur.execute("insert into coulomb_catalog values('{}','{}')".format('PRICE','70000 $'))
    obj.commit()
    cur.execute("insert into coulomb_catalog values('{}','{}')".format('PRICE+TAX','80000$'))
    obj.commit()
    cur.execute("insert into coulomb_catalog values('{}','{}')".format('SEATS','7'))
    obj.commit()
    obj.close()
def cybertruck_catalog():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('cybertruck_catalog',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table cybertruck_catalog')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table cybertruck_catalog(SPECIFICATION VARCHAR(60),DETAILS VARCHAR(60))')
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into cybertruck_catalog values('{}','{}')".format('CAR NAME','CYBERTRUCK'))
    obj.commit()
    cur.execute("insert into cybertruck_catalog values('{}','{}')".format('POWER STEARING','NO'))
    obj.commit()
    cur.execute("insert into cybertruck_catalog values('{}','{}')".format('AIRBAGS','4'))
    obj.commit()
    cur.execute("insert into cybertruck_catalog values('{}','{}')".format('FOR LIGHT','YES'))
    obj.commit()
    cur.execute("insert into cybertruck_catalog values('{}','{}')".format('AIR CONDITIONER','YES'))
    obj.commit()
    cur.execute("insert into cybertruck_catalog values('{}','{}')".format('WARRENTY','22 YEARS'))
    obj.commit()
    cur.execute("insert into cybertruck_catalog values('{}','{}')".format('CHARGING TIME','9 HOURS'))
    obj.commit()
    cur.execute("insert into cybertruck_catalog values('{}','{}')".format('DISTANCE WITH SINGLE CHARGE','800 Km'))
    obj.commit()
    cur.execute("insert into cybertruck_catalog values('{}','{}')".format('FUEL TYPE','ELECTRIC'))
    obj.commit()
    cur.execute("insert into cybertruck_catalog values('{}','{}')".format('BOOT SPACE','450 Lts'))
    obj.commit()
    cur.execute("insert into cybertruck_catalog values('{}','{}')".format('ADDITIONAL QUALITIES','BULLETPROOF'))
    obj.commit()
    cur.execute("insert into cybertruck_catalog values('{}','{}')".format('PRICE','120000 $'))
    obj.commit()
    cur.execute("insert into cybertruck_catalog values('{}','{}')".format('PRICE+TAX','130000$'))
    obj.commit()
    cur.execute("insert into cybertruck_catalog values('{}','{}')".format('SEATS','4'))
    obj.commit()
    obj.close()
def mega_catalog():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('mega_catalog',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table mega_catalog')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table mega_catalog(SPECIFICATION VARCHAR(60),DETAILS VARCHAR(60))')
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into mega_catalog values('{}','{}')".format('CAR NAME','MEGA'))
    obj.commit()
    cur.execute("insert into mega_catalog values('{}','{}')".format('POWER STEARING','NO'))
    obj.commit()
    cur.execute("insert into mega_catalog values('{}','{}')".format('AIRBAGS','NIL'))
    obj.commit()
    cur.execute("insert into mega_catalog values('{}','{}')".format('FOR LIGHT','YES'))
    obj.commit()
    cur.execute("insert into mega_catalog values('{}','{}')".format('AIR CONDITIONER','NO'))
    obj.commit()
    cur.execute("insert into mega_catalog values('{}','{}')".format('WARRENTY','23 YEARS'))
    obj.commit()
    cur.execute("insert into mega_catalog values('{}','{}')".format('CHARGING TIME','3 HOURS'))
    obj.commit()
    cur.execute("insert into mega_catalog values('{}','{}')".format('DISTANCE WITH SINGLE CHARGE','500 Km'))
    obj.commit()
    cur.execute("insert into mega_catalog values('{}','{}')".format('FUEL TYPE','ELECTRIC'))
    obj.commit()
    cur.execute("insert into mega_catalog values('{}','{}')".format('BOOT SPACE','450 Lts'))
    obj.commit()
    cur.execute("insert into mega_catalog values('{}','{}')".format('ADDITIONAL QUALITIES','OFF ROADER'))
    obj.commit()
    cur.execute("insert into mega_catalog values('{}','{}')".format('PRICE','65000 $'))
    obj.commit()
    cur.execute("insert into mega_catalog values('{}','{}')".format('PRICE+TAX','75000$'))
    obj.commit()
    cur.execute("insert into mega_catalog values('{}','{}')".format('SEATS','4'))
    obj.commit()
    obj.close()
def s_catalog():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('s_catalog',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table s_catalog')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table s_catalog(SPECIFICATION VARCHAR(60),DETAILS VARCHAR(60))')
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into s_catalog values('{}','{}')".format('CAR NAME','MODEL S'))
    obj.commit()
    cur.execute("insert into s_catalog values('{}','{}')".format('POWER STEARING','YES'))
    obj.commit()
    cur.execute("insert into s_catalog values('{}','{}')".format('AIRBAGS','NIL'))
    obj.commit()
    cur.execute("insert into s_catalog values('{}','{}')".format('FOR LIGHT','NO'))
    obj.commit()
    cur.execute("insert into s_catalog values('{}','{}')".format('AIR CONDITIONER','NO'))
    obj.commit()
    cur.execute("insert into s_catalog values('{}','{}')".format('WARRENTY','20 YEARS'))
    obj.commit()
    cur.execute("insert into s_catalog values('{}','{}')".format('CHARGING TIME','6 HOURS'))
    obj.commit()
    cur.execute("insert into s_catalog values('{}','{}')".format('DISTANCE WITH SINGLE CHARGE','200 Km'))
    obj.commit()
    cur.execute("insert into s_catalog values('{}','{}')".format('FUEL TYPE','ELECTRIC'))
    obj.commit()
    cur.execute("insert into s_catalog values('{}','{}')".format('BOOT SPACE','150 Lts'))
    obj.commit()
    cur.execute("insert into s_catalog values('{}','{}')".format('ADDITIONAL QUALITIES','NIL'))
    obj.commit()
    cur.execute("insert into s_catalog values('{}','{}')".format('PRICE','45000 $'))
    obj.commit()
    cur.execute("insert into s_catalog values('{}','{}')".format('PRICE+TAX','55000$'))
    obj.commit()
    cur.execute("insert into s_catalog values('{}','{}')".format('SEATS','4'))
    obj.commit()
    obj.close()
def x_catalog():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('x_catalog',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table x_catalog')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table x_catalog(SPECIFICATION VARCHAR(60),DETAILS VARCHAR(60))')
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into x_catalog values('{}','{}')".format('CAR NAME','MODEL X'))
    obj.commit()
    cur.execute("insert into x_catalog values('{}','{}')".format('POWER STEARING','YES'))
    obj.commit()
    cur.execute("insert into x_catalog values('{}','{}')".format('AIRBAGS','NIL'))
    obj.commit()
    cur.execute("insert into x_catalog values('{}','{}')".format('FOR LIGHT','YES'))
    obj.commit()
    cur.execute("insert into x_catalog values('{}','{}')".format('AIR CONDITIONER','YES'))
    obj.commit()
    cur.execute("insert into x_catalog values('{}','{}')".format('WARRENTY','21 YEARS'))
    obj.commit()
    cur.execute("insert into x_catalog values('{}','{}')".format('CHARGING TIME','7 HOURS'))
    obj.commit()
    cur.execute("insert into x_catalog values('{}','{}')".format('DISTANCE WITH SINGLE CHARGE','300 Km'))
    obj.commit()
    cur.execute("insert into x_catalog values('{}','{}')".format('FUEL TYPE','ELECTRIC'))
    obj.commit()
    cur.execute("insert into x_catalog values('{}','{}')".format('BOOT SPACE','300 Lts'))
    obj.commit()
    cur.execute("insert into x_catalog values('{}','{}')".format('ADDITIONAL QUALITIES','SMOOTH TRAVEL'))
    obj.commit()
    cur.execute("insert into x_catalog values('{}','{}')".format('PRICE','48000 $'))
    obj.commit()
    cur.execute("insert into x_catalog values('{}','{}')".format('PRICE+TAX','58000$'))
    obj.commit()
    cur.execute("insert into x_catalog values('{}','{}')".format('SEATS','4'))
    obj.commit()
    obj.close()
def y_catalog():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('y_catalog',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table y_catalog')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table y_catalog(SPECIFICATION VARCHAR(60),DETAILS VARCHAR(60))')
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into y_catalog values('{}','{}')".format('CAR NAME','MODEL Y'))
    obj.commit()
    cur.execute("insert into y_catalog values('{}','{}')".format('POWER STEARING','YES'))
    obj.commit()
    cur.execute("insert into y_catalog values('{}','{}')".format('AIRBAGS','8'))
    obj.commit()
    cur.execute("insert into y_catalog values('{}','{}')".format('FOR LIGHT','YES'))
    obj.commit()
    cur.execute("insert into y_catalog values('{}','{}')".format('AIR CONDITIONER','YES'))
    obj.commit()
    cur.execute("insert into y_catalog values('{}','{}')".format('WARRENTY','22 YEARS'))
    obj.commit()
    cur.execute("insert into y_catalog values('{}','{}')".format('CHARGING TIME','6 HOURS'))
    obj.commit()
    cur.execute("insert into y_catalog values('{}','{}')".format('DISTANCE WITH SINGLE CHARGE','400 Km'))
    obj.commit()
    cur.execute("insert into y_catalog values('{}','{}')".format('FUEL TYPE','ELECTRIC'))
    obj.commit()
    cur.execute("insert into y_catalog values('{}','{}')".format('BOOT SPACE','600 Lts'))
    obj.commit()
    cur.execute("insert into y_catalog values('{}','{}')".format('ADDITIONAL QUALITIES','SMOOTH TRAVEL'))
    obj.commit()
    cur.execute("insert into y_catalog values('{}','{}')".format('PRICE','55000 $'))
    obj.commit()
    cur.execute("insert into y_catalog values('{}','{}')".format('PRICE+TAX','65000$'))
    obj.commit()
    cur.execute("insert into y_catalog values('{}','{}')".format('SEATS','7'))
    obj.commit()
    obj.close()
def semi_catalog():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('semi_catalog',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table semi_catalog')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table semi_catalog(SPECIFICATION VARCHAR(60),DETAILS VARCHAR(60))')
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into semi_catalog values('{}','{}')".format('CAR NAME','SEMI'))
    obj.commit()
    cur.execute("insert into semi_catalog values('{}','{}')".format('POWER STEARING','YES'))
    obj.commit()
    cur.execute("insert into semi_catalog values('{}','{}')".format('AIRBAGS','4'))
    obj.commit()
    cur.execute("insert into semi_catalog values('{}','{}')".format('FOR LIGHT','YES'))
    obj.commit()
    cur.execute("insert into semi_catalog values('{}','{}')".format('AIR CONDITIONER','YES'))
    obj.commit()
    cur.execute("insert into semi_catalog values('{}','{}')".format('WARRENTY','28 YEARS'))
    obj.commit()
    cur.execute("insert into semi_catalog values('{}','{}')".format('CHARGING TIME','14 HOURS'))
    obj.commit()
    cur.execute("insert into semi_catalog values('{}','{}')".format('DISTANCE WITH SINGLE CHARGE','1000 Km'))
    obj.commit()
    cur.execute("insert into semi_catalog values('{}','{}')".format('FUEL TYPE','ELECTRIC'))
    obj.commit()
    cur.execute("insert into semi_catalog values('{}','{}')".format('BOOT SPACE','600 Lts'))
    obj.commit()
    cur.execute("insert into semi_catalog values('{}','{}')".format('ADDITIONAL QUALITIES','LARGE STORAGE'))
    obj.commit()
    cur.execute("insert into semi_catalog values('{}','{}')".format('PRICE','200000 $'))
    obj.commit()
    cur.execute("insert into semi_catalog values('{}','{}')".format('PRICE+TAX','250000$'))
    obj.commit()
    cur.execute("insert into semi_catalog values('{}','{}')".format('SEATS','2'))
    obj.commit()
    obj.close()
def zetar_catalog():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('zetar_catalog',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table zetar_catalog')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table zetar_catalog(SPECIFICATION VARCHAR(60),DETAILS VARCHAR(60))')
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into zetar_catalog values('{}','{}')".format('CAR NAME','ZETAR'))
    obj.commit()
    cur.execute("insert into zetar_catalog values('{}','{}')".format('POWER STEARING','YES'))
    obj.commit()
    cur.execute("insert into zetar_catalog values('{}','{}')".format('AIRBAGS','6'))
    obj.commit()
    cur.execute("insert into zetar_catalog values('{}','{}')".format('FOR LIGHT','YES'))
    obj.commit()
    cur.execute("insert into zetar_catalog values('{}','{}')".format('AIR CONDITIONER','YES'))
    obj.commit()
    cur.execute("insert into zetar_catalog values('{}','{}')".format('WARRENTY','27 YEARS'))
    obj.commit()
    cur.execute("insert into zetar_catalog values('{}','{}')".format('CHARGING TIME','13 HOURS'))
    obj.commit()
    cur.execute("insert into zetar_catalog values('{}','{}')".format('DISTANCE WITH SINGLE CHARGE','500 Km'))
    obj.commit()
    cur.execute("insert into zetar_catalog values('{}','{}')".format('FUEL TYPE','ELECTRIC'))
    obj.commit()
    cur.execute("insert into zetar_catalog values('{}','{}')".format('BOOT SPACE','300 Lts'))
    obj.commit()
    cur.execute("insert into zetar_catalog values('{}','{}')".format('ADDITIONAL QUALITIES','BULLETPROOF'))
    obj.commit()
    cur.execute("insert into zetar_catalog values('{}','{}')".format('PRICE','150000 $'))
    obj.commit()
    cur.execute("insert into zetar_catalog values('{}','{}')".format('PRICE+TAX','180000$'))
    obj.commit()
    cur.execute("insert into zetar_catalog values('{}','{}')".format('SEATS','4'))
    obj.commit()
    obj.close()
def departments():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('departments',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table departments')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table departments(DEPT_NAME VARCHAR(80),NUM_EMPLOYEE VARCHAR(80),DEPT_HEAD VARCHAR(80),INVEST_PER_EMP INT,EARN_PER_EMP INT,BUDGET INT)')
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into departments values('MARKETING','5','TINLEY',40000,50000,0)")
    obj.commit()
    cur.execute("insert into departments values('MANUFACTURING','6','ELLA',40000,62000,0)")
    obj.commit()
    cur.execute("insert into departments values('HR','5','TATUM',40000,80000,0)")
    obj.commit()
    cur.execute("insert into departments values('PURCHASE','5','SHILOH',40000,71000,0)")
    obj.commit()
    obj.close()
departments()
def employees():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('employee',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table employee')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table employee(EMP_ID VARCHAR(20),EMP_NAME VARCHAR(80),DEPARTMENT VARCHAR(80),DESIGNATION VARCHAR(80),SALARY INT,DOJ DATE,POINTS INT,NO_WARNINGS INT,BONUS INT)')
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN001','TINLEY','MARKETING','DGM',50000,'2005-01-01',20,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN002','HOLDEN','MARKETING','CHIEF MANAGER',40000,'2006-01-01',18,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN003','BLAINE','MARKETING','SR. MANAGER',35000,'2007-01-01',16,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN004','DOLOVAN','MARKETING','MANAGER',30000,'2008-01-01',14,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN005','PRESTON','MARKETING','ENGINEER',20000,'2009-01-01',12,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN006','ELLA','MANUFACTURING','DGM',50000,'2005-01-01',20,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN007','TOM','MANUFACTURING','CHIEF MANAGER',40000,'2006-01-01',18,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN008','DECK','MANUFACTURING','SR. MANAGER',35000,'2007-01-01',16,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN009','HARRY','MANUFACTURING','MANAGER',30000,'2008-01-01',14,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN010','JAMES','MANUFACTURING','ENGINEER',20000,'2009-01-01',12,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN011','TATUM','HR','DGM',50000,'2005-01-01',20,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN012','WILLIAM','HR','CHIEF MANAGER',40000,'2006-01-01',18,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN013','SHAWN','HR','SR. MANAGER',35000,'2007-01-01',16,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN014','HENRY','HR','MANAGER',30000,'2008-01-01',14,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN015','MARGRET','HR','ENGINEER',20000,'2009-01-01',12,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN016','SHILOH','PURCHASE','DGM',50000,'2005-01-01',20,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN017','SAMUEL','PURCHASE','CHIEF MANAGER',40000,'2006-01-01',18,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN018','GAMBART','PURCHASE','SR. MANAGER',35000,'2007-01-01',16,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN019','BROCK','PURCHASE','MANAGER',30000,'2008-01-01',14,0,0))
    obj.commit()
    cur.execute("insert into employee values('{}','{}','{}','{}',{},'{}',{},{},{})".format('CAN020','ASHLEY','PURCHASE','ENGINEER',20000,'2009-01-01',12,0,0))
    obj.commit()
    obj.close()
def one_activity():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('one_activity',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table one_activity')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table one_activity(SNO INT,NAME VARCHAR(80),NO_PEOPLE INT,DURATION VARCHAR(80),SCHEDULED VARCHAR(80))')
    obj.commit()
    obj.close()
def two_activity():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('two_activity',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table two_activity')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table two_activity(SNO INT,NAME VARCHAR(80),NO_PEOPLE INT,DURATION VARCHAR(80),SCHEDULED VARCHAR(80))')
    obj.commit()
    obj.close()
def three_activity():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('three_activity',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table three_activity')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table three_activity(SNO INT,NAME VARCHAR(80),NO_PEOPLE INT,DURATION VARCHAR(80),SCHEDULED VARCHAR(80))')
    obj.commit()
    obj.close()
def four_activity():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('four_activity',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table four_activity')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table four_activity(SNO INT,NAME VARCHAR(80),NO_PEOPLE INT,DURATION VARCHAR(80),SCHEDULED VARCHAR(80))')
    obj.commit()
    obj.close()
def investors():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('investors',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table investors')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table investors(SNO VARCHAR(80),NAME VARCHAR(80),DESIGNATION VARCHAR(80),IN_EQUITY VARCHAR(80),IN_DEBT VARCHAR(80))')
    obj.commit()
    obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("INSERT INTO INVESTORS VALUES('{}','{}','{}','{}','{}')".format('1.','Mr.Avighna Tripathi','Co-founder and CEO of Candela Automotives','90 million $ at 25% equity','NIL'))
    obj.commit()
    cur.execute("INSERT INTO INVESTORS VALUES('{}','{}','{}','{}','{}')".format('2.','Mr.Divyansh Mishra','Co-founder and CTO of Candela Automotives','90 million $ at 25% equity','NIL'))
    obj.commit()
    cur.execute("INSERT INTO INVESTORS VALUES('{}','{}','{}','{}','{}')".format('3.','Ms. Alice Walton','Owner of walmart','10 million $ at 5% equity','2 million $ at 12% per annum'))
    obj.commit()
    cur.execute("INSERT INTO INVESTORS VALUES('{}','{}','{}','{}','{}')".format('4.','Mr.Ratan Tata','former chairperson of Tata group','10 million $ at 5% equity','1 million $ at 10% per annum'))
    obj.commit()
    cur.execute("INSERT INTO INVESTORS VALUES('{}','{}','{}','{}','{}')".format('5.','Ms.Ghazal Alagh','Co-founder and CEO of Mamaearth cosmetics','10 million $ at 5% equity','1 million $ at 8% per annum'))
    obj.commit()
    obj.close()
def manufacturing_stocks():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('manufacturing_stocks',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table manufacturing_stocks')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table manufacturing_stocks(SNO VARCHAR(80),MATERIAL VARCHAR(80),QUALITY VARCHAR(80),UNIT VARCHAR(80),STOCK INT)')
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('1.','Steel','EXCELLENT','Metric ton',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('2.','Steel','GOOD','Metric ton',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('3.','Steel','SATISFACTORY','Metric ton',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('4.','Ion battery','EXCELLENT','Piece',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('5.','Ion battery','GOOD','Piece',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('6.','Ion battery','SATISFACTORY','Piece',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('7.','Rubber','EXCELLENT','Metric ton',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('8.','Rubber','GOOD','Metric ton',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('9.','Rubber','SATISFACTORY','Metric ton',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('10.','Plastic','EXCELLENT','Metric ton',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('11.','Plastic','GOOD','Metric ton',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('12.','Plastic','SATISFACTORY','Metric ton',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('13.','Glass','EXCELLENT','Metric ton',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('14.','Glass','GOOD','Metric ton',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('15.','Glass','SATISFACTORY','Metric ton',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('16.','Leather','EXCELLENT','Square feet',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('17.','Leather','GOOD','Square feet',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('18.','Leather','SATISFACTORY','Square feet',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('19.','Solar battery','EXCELLENT','Pieces',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('20.','Solar battery','GOOD','Pieces',0))
    obj.commit()
    cur.execute("INSERT INTO MANUFACTURING_STOCKS VALUES('{}','{}','{}','{}',{})".format('21.','Solar battery','SATISFACTORY','Pieces',0))
    obj.commit()
    obj.close()
def sales_per_quater():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('sales_per_quater',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table sales_per_quater')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table sales_per_quater(MODEL VARCHAR(80),INVESTMENTS INT,TARGET_QUATER VARCHAR(80),ACTUAL_SALES VARCHAR(80),RETURNS INT)')
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("INSERT INTO SALES_PER_QUATER VALUES('{}',{},'{}','{}',{})".format('S',20000000,'900 MODELS','1125 MODELS',30000000))
    obj.commit()
    cur.execute("INSERT INTO SALES_PER_QUATER VALUES('{}',{},'{}','{}',{})".format('X',20000000,'900 MODELS','725 MODELS',40000000))
    obj.commit()
    cur.execute("INSERT INTO SALES_PER_QUATER VALUES('{}',{},'{}','{}',{})".format('Y',20000000,'900 MODELS','1256 MODELS',50000000))
    obj.commit()
    cur.execute("INSERT INTO SALES_PER_QUATER VALUES('{}',{},'{}','{}',{})".format('M',20000000,'900 MODELS','2156 MODELS',60000000))
    obj.commit()
    cur.execute("INSERT INTO SALES_PER_QUATER VALUES('{}',{},'{}','{}',{})".format('C',20000000,'900 MODELS','1056 MODELS',70000000))
    obj.commit()
    cur.execute("INSERT INTO SALES_PER_QUATER VALUES('{}',{},'{}','{}',{})".format('D',20000000,'900 MODELS','1325 MODELS',80000000))
    obj.commit()
    cur.execute("INSERT INTO SALES_PER_QUATER VALUES('{}',{},'{}','{}',{})".format('T',20000000,'900 MODELS','1000 MODELS',90000000))
    obj.commit()
    cur.execute("INSERT INTO SALES_PER_QUATER VALUES('{}',{},'{}','{}',{})".format('Z',20000000,'900 MODELS','1010 MODELS',100000000))
    obj.commit()
    cur.execute("INSERT INTO SALES_PER_QUATER VALUES('{}',{},'{}','{}',{})".format('F',20000000,'900 MODELS','1050 MODELS',110000000))
    obj.commit()
    cur.execute("INSERT INTO SALES_PER_QUATER VALUES('{}',{},'{}','{}',{})".format('DT',20000000,'900 MODELS','2056 MODELS',120000000))
    obj.commit()
    obj.close()
def showrooms():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('showrooms',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table showrooms')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table showrooms(SNO INT,CITY VARCHAR(80),IN_AREA VARCHAR(80),MOB_NO INT)')
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("INSERT INTO SHOWROOMS VALUES({},'{}','{}',{})".format(1,'Ahmedabad','Gandhi chowk',1800662723))
    obj.commit()
    cur.execute("INSERT INTO SHOWROOMS VALUES({},'{}','{}',{})".format(2,'Chennai','Gandhi chowk',1800662724))
    obj.commit()
    cur.execute("INSERT INTO SHOWROOMS VALUES({},'{}','{}',{})".format(3,'Delhi','Gandhi chowk',1800662725))
    obj.commit()
    cur.execute("INSERT INTO SHOWROOMS VALUES({},'{}','{}',{})".format(4,'Kolkata','Gandhi chowk',1800662726))
    obj.commit()
    cur.execute("INSERT INTO SHOWROOMS VALUES({},'{}','{}',{})".format(5,'Lucknow','Gandhi chowk',1800662727))
    obj.commit()
    cur.execute("INSERT INTO SHOWROOMS VALUES({},'{}','{}',{})".format(6,'Kanpur','Gandhi chowk',1800662728))
    obj.commit()
    cur.execute("INSERT INTO SHOWROOMS VALUES({},'{}','{}',{})".format(7,'Mumbai','Gandhi chowk',1800662729))
    obj.commit()
    cur.execute("INSERT INTO SHOWROOMS VALUES({},'{}','{}',{})".format(8,'Los Angeles','Gandhi chowk',1800662730))
    obj.commit()
    cur.execute("INSERT INTO SHOWROOMS VALUES({},'{}','{}',{})".format(9,'New York City','Gandhi chowk',1800662731))
    obj.commit()
    cur.execute("INSERT INTO SHOWROOMS VALUES({},'{}','{}',{})".format(10,'Moskow','Gandhi chowk',1800662732))
    obj.commit()
    obj.close()
def stocks_store():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('stocks_store',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table stocks_store')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table stocks_store(SNO VARCHAR(80),MATERIAL VARCHAR(80),QUALITY VARCHAR(80),UNIT VARCHAR(80),CRI_MIN INT,CRI_MAX INT,STOCK INT)')
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('1.','Steel','EXCELLENT','Metric ton',2,20,2))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('2.','Steel','GOOD','Metric ton',2,20,2))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('3.','Steel','SATISFACTORY','Metric ton',2,20,2))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('4.','Ion battery','EXCELLENT','Piece',2000,10000,2000))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('5.','Ion battery','GOOD','Piece',2000,10000,2000))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('6.','Ion battery','SATISFACTORY','Piece',2000,10000,2000))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('7.','Rubber','EXCELLENT','Metric ton',2000,8000,2000))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('8.','Rubber','GOOD','Metric ton',2000,8000,2000))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('9.','Rubber','SATISFACTORY','Metric ton',2000,8000,2000))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('10.','Plastic','EXCELLENT','Metric ton',4000,20000,4000))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('11.','Plastic','GOOD','Metric ton',4000,20000,4000))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('12.','Plastic','SATISFACTORY','Metric ton',4000,20000,4000))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('13.','Glass','EXCELLENT','Metric ton',80,2000,80))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('14.','Glass','GOOD','Metric ton',80,2000,80))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('15.','Glass','SATISFACTORY','Metric ton',80,2000,80))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('16.','Leather','EXCELLENT','Square feet',2000,10000,2000))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('17.','Leather','GOOD','Square feet',2000,10000,2000))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('18.','Leather','SATISFACTORY','Square feet',2000,10000,2000))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('19.','Solar battery','EXCELLENT','Pieces',1000,8000,1000))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('20.','Solar battery','GOOD','Pieces',1000,8000,1000))
    obj.commit()
    cur.execute("INSERT INTO stocks_store VALUES('{}','{}','{}','{}',{},{},{})".format('21.','Solar battery','SATISFACTORY','Pieces',1000,8000,1000))
    obj.commit()
    obj.close()
def store():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('store',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table store')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table store(SNO VARCHAR(80),MATERIAL VARCHAR(80),QUALITY VARCHAR(80),UNIT VARCHAR(80),CRI_MIN INT,CRI_MAX INT,NET_PRICE INT)')
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('1.','Steel','EXCELLENT','Metric ton',2,20,50000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('2.','Steel','GOOD','Metric ton',2,20,48000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('3.','Steel','SATISFACTORY','Metric ton',2,20,45000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('4.','Ion battery','EXCELLENT','Piece',2000,10000,30000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('5.','Ion battery','GOOD','Piece',2000,10000,25000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('6.','Ion battery','SATISFACTORY','Piece',2000,10000,20000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('7.','Rubber','EXCELLENT','Metric ton',2000,8000,150000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('8.','Rubber','GOOD','Metric ton',2000,8000,100000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('9.','Rubber','SATISFACTORY','Metric ton',2000,8000,50000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('10.','Dyed Plastic','EXCELLENT','Metric ton',4000,20000,3000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('11.','Dyed Plastic','GOOD','Metric ton',4000,20000,25000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('12.','Dyed Plastic','SATISFACTORY','Metric ton',4000,20000,20000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('13.','Glass','EXCELLENT','Metric ton',80,2000,18000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('14.','Glass','GOOD','Metric ton',80,2000,18000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('15.','Glass','SATISFACTORY','Metric ton',80,2000,18000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('16.','Leather','EXCELLENT','Square feet',2000,10000,50000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('17.','Leather','GOOD','Square feet',2000,10000,50000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('18.','Leather','SATISFACTORY','Square feet',2000,10000,40000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('19.','Solar battery','EXCELLENT','Pieces',1000,8000,15000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('20.','Solar battery','GOOD','Pieces',1000,8000,12000))
    obj.commit()
    cur.execute("INSERT INTO store VALUES('{}','{}','{}','{}',{},{},{})".format('21.','Solar battery','SATISFACTORY','Pieces',1000,8000,10000))
    obj.commit()
    obj.close()
def tied_company():
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('show tables')
    d=cur.fetchall()
    obj.close()
    f=('tied_company',)
    if f in d:
        obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
        cur=obj.cursor()
        cur.execute('drop table tied_company')
        obj.commit()
        obj.close()
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute('create table tied_company(NAME VARCHAR(80),COMP_CEO VARCHAR(80),PROVIDED VARCHAR(80),TO_US VARCHAR(80))')
    obj=mycon.connect(host='localhost',user='root',password='root123',database='CANDELA')
    cur=obj.cursor()
    cur.execute("INSERT INTO tied_company VALUES('{}','{}','{}','{}')".format('GOOGLE','MR. SUNDAR PICHAI','EXTENDED NETWORKS','AI AND DIGITALS'))
    obj.commit()
    cur.execute("INSERT INTO tied_company VALUES('{}','{}','{}','{}')".format('RELIANCE','MR. ANIL AMBANI','MARKETING','ELECTRICITY AND FACTORY FUELS'))
    obj.commit()
    cur.execute("INSERT INTO tied_company VALUES('{}','{}','{}','{}')".format('RELIANCE','MR. MUKESH AMBANI','INVESTMENTS','TELECOMMUNICATIONS'))
    obj.commit()
    cur.execute("INSERT INTO tied_company VALUES('{}','{}','{}','{}')".format('BORING COMPANY','MR. ELON MUSK','TUNNELS','BORING AUTOMOTIVES'))
    obj.commit()
    obj.close()
activity()
applicants()
catalog()
s_catalog()
x_catalog()
y_catalog()
coulomb_catalog()
deca_catalog()
mega_catalog()
semi_catalog()
zetar_catalog()
cybertruck_catalog()
one_activity()
two_activity()
three_activity()
four_activity()
departments()
employees()
store()
stocks_store()
manufacturing_stocks()
showrooms()
tied_company()
investors()
sales_per_quater()
